[project]
name = "rune-workspace"
version = "26.6.37"

[tool.bumpver]
current_version = "26.6.37"
version_pattern = "YY.MM.INC0"
commit = false
tag = false
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"apps/rune-cli/pyproject.toml" = [
    'version = "{version}"',
]
