[project]
name = "rune-cli"
version = "26.6.16"
description = "Rune CLI"
authors = [
    {name = "Aryan Singh", email = "aquiveal@gmail.com"},
]
dependencies = ["typer>=0.15.2", "pydantic>=2.13.3", "pyyaml>=6.0.1", "questionary>=2.1.0"]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
rune = "rune.main:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
]
